[package]
name = "ion-schema-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ion-rs = "0.6.0"
thiserror = "1.0"

[dev-dependencies]
rstest = "0.9"
clap = {version = "2.33.3", features = ["yaml"]}
