name: CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
            submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Rustfmt
        run: cargo fmt --verbose -- --check
      # `clippy-check` will run `cargo clippy` on new pull requests. Due to a limitation in GitHub
      # permissions, the behavior of the Action is different depending on the source of the PR. If the
      # PR comes from the ion-schema-rust project itself, any suggestions will be added to the PR as comments.
      # If the PR comes from a fork, any suggestions will be added to the Action's STDOUT for review.
      # For details, see: https://github.com/actions-rs/clippy-check/issues/2
      - name: Install Clippy
        # The clippy check depends on setup steps defined above, but we don't want it to run
        # for every OS because it posts its comments to the PR. These `if` checks limit clippy to
        # only running on the Linux test. (The choice of OS was arbitrary.)
        if: matrix.os == 'ubuntu-latest'
        run: rustup component add clippy
      - name: Run Clippy
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/clippy-check@v1
        with:
          # Adding comments to the PR requires the GITHUB_TOKEN secret.
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
